#ifndef SMMU_REGS_H__
#define SMMU_REGS_H__

#include <stdint.h>

#include "system.h"

#define TCU_NODE_CTRL_OFFSET (uint32_t)(0x9000)
#define TCU_NODE_STATUS_OFFSET (uint32_t)(0x9400)

typedef struct __attribute__((packed)) __attribute__((aligned(4))) {
    volatile uint32_t SMMU_IDR0;                   /* SMMU_TCU_SMMU_IDR0 */
    volatile uint32_t SMMU_IDR1;                   /* SMMU_TCU_SMMU_IDR1 */
    volatile uint32_t SMMU_IDR2;                   /* SMMU_TCU_SMMU_IDR2 */
    volatile uint32_t SMMU_IDR3;                   /* SMMU_TCU_SMMU_IDR3 */
    volatile uint32_t _pad_0x10_0x13;              /* *UNDEFINED* */
    volatile uint32_t SMMU_IDR5;                   /* SMMU_TCU_SMMU_IDR5 */
    volatile uint32_t SMMU_IIDR;                   /* SMMU_TCU_SMMU_IIDR */
    volatile uint32_t SMMU_AIDR;                   /* SMMU_TCU_SMMU_AIDR */
    volatile uint32_t SMMU_CR0;                    /* SMMU_TCU_SMMU_CR0 */
    volatile uint32_t SMMU_CR0ACK;                 /* SMMU_TCU_SMMU_CR0ACK */
    volatile uint32_t SMMU_CR1;                    /* SMMU_TCU_SMMU_CR1 */
    volatile uint32_t SMMU_CR2;                    /* SMMU_TCU_SMMU_CR2 */
    volatile uint32_t _pad_0x30_0x43[5];           /* *UNDEFINED* */
    volatile uint32_t SMMU_GBPA;                   /* SMMU_TCU_SMMU_GBPA */
    volatile uint32_t _pad_0x48_0x4f[2];           /* *UNDEFINED* */
    volatile uint32_t SMMU_IRQ_CTRL;               /* SMMU_TCU_SMMU_IRQ_CTRL */
    volatile uint32_t SMMU_IRQ_CTRLACK;            /* SMMU_TCU_SMMU_IRQ_CTRLACK */
    volatile uint32_t _pad_0x58_0x5f[2];           /* *UNDEFINED* */
    volatile uint32_t SMMU_GERROR;                 /* SMMU_TCU_SMMU_GERROR */
    volatile uint32_t SMMU_GERRORN;                /* SMMU_TCU_SMMU_GERRORN */
    volatile uint32_t SMMU_GERROR_IRQ_CFG0_LO;     /* SMMU_TCU_SMMU_GERROR_IRQ_CFG0_LO */
    volatile uint32_t SMMU_GERROR_IRQ_CFG0_HI;     /* SMMU_TCU_SMMU_GERROR_IRQ_CFG0_HI */
    volatile uint32_t SMMU_GERROR_IRQ_CFG1;        /* SMMU_TCU_SMMU_GERROR_IRQ_CFG1 */
    volatile uint32_t SMMU_GERROR_IRQ_CFG2;        /* SMMU_TCU_SMMU_GERROR_IRQ_CFG2 */
    volatile uint32_t _pad_0x78_0x7f[2];           /* *UNDEFINED* */
    volatile uint32_t SMMU_STRTAB_BASE_LO;         /* SMMU_TCU_SMMU_STRTAB_BASE_LO */
    volatile uint32_t SMMU_STRTAB_BASE_HI;         /* SMMU_TCU_SMMU_STRTAB_BASE_HI */
    volatile uint32_t SMMU_STRTAB_BASE_CFG;        /* SMMU_TCU_SMMU_STRTAB_BASE_CFG */
    volatile uint32_t _pad_0x8c_0x8f;              /* *UNDEFINED* */
    volatile uint32_t SMMU_CMDQ_BASE_LO;           /* SMMU_TCU_SMMU_CMDQ_BASE_LO */
    volatile uint32_t SMMU_CMDQ_BASE_HI;           /* SMMU_TCU_SMMU_CMDQ_BASE_HI */
    volatile uint32_t SMMU_CMDQ_PROD;              /* SMMU_TCU_SMMU_CMDQ_PROD */
    volatile uint32_t SMMU_CMDQ_CONS;              /* SMMU_TCU_SMMU_CMDQ_CONS */
    volatile uint32_t SMMU_EVENTQ_BASE_LO;         /* SMMU_TCU_SMMU_EVENTQ_BASE_LO */
    volatile uint32_t SMMU_EVENTQ_BASE_HI;         /* SMMU_TCU_SMMU_EVENTQ_BASE_HI */
    volatile uint32_t _pad_0xa8_0xaf[2];           /* *UNDEFINED* */
    volatile uint32_t SMMU_EVENTQ_IRQ_CFG0_LO;     /* SMMU_TCU_SMMU_EVENTQ_IRQ_CFG0_LO */
    volatile uint32_t SMMU_EVENTQ_IRQ_CFG0_HI;     /* SMMU_TCU_SMMU_EVENTQ_IRQ_CFG0_HI */
    volatile uint32_t SMMU_EVENTQ_IRQ_CFG1;        /* SMMU_TCU_SMMU_EVENTQ_IRQ_CFG1 */
    volatile uint32_t SMMU_EVENTQ_IRQ_CFG2;        /* SMMU_TCU_SMMU_EVENTQ_IRQ_CFG2 */
    volatile uint32_t SMMU_PRIQ_BASE_LO;           /* SMMU_TCU_SMMU_PRIQ_BASE_LO */
    volatile uint32_t SMMU_PRIQ_BASE_HI;           /* SMMU_TCU_SMMU_PRIQ_BASE_HI */
    volatile uint32_t _pad_0xc8_0xcf[2];           /* *UNDEFINED* */
    volatile uint32_t SMMU_PRIQ_IRQ_CFG0_LO;       /* SMMU_TCU_SMMU_PRIQ_IRQ_CFG0_LO */
    volatile uint32_t SMMU_PRIQ_IRQ_CFG0_HI;       /* SMMU_TCU_SMMU_PRIQ_IRQ_CFG0_HI */
    volatile uint32_t SMMU_PRIQ_IRQ_CFG1;          /* SMMU_TCU_SMMU_PRIQ_IRQ_CFG1 */
    volatile uint32_t SMMU_PRIQ_IRQ_CFG2;          /* SMMU_TCU_SMMU_PRIQ_IRQ_CFG2 */
    volatile uint32_t _pad_0xe0_0xfcf[956];        /* *UNDEFINED* */
    volatile uint32_t SMMU_PIDR4;                  /* SMMU_TCU_SMMU_PIDR4 */
    volatile uint32_t SMMU_PIDR5;                  /* SMMU_TCU_SMMU_PIDR5 */
    volatile uint32_t SMMU_PIDR6;                  /* SMMU_TCU_SMMU_PIDR6 */
    volatile uint32_t SMMU_PIDR7;                  /* SMMU_TCU_SMMU_PIDR7 */
    volatile uint32_t SMMU_PIDR0;                  /* SMMU_TCU_SMMU_PIDR0 */
    volatile uint32_t SMMU_PIDR1;                  /* SMMU_TCU_SMMU_PIDR1 */
    volatile uint32_t SMMU_PIDR2;                  /* SMMU_TCU_SMMU_PIDR2 */
    volatile uint32_t SMMU_PIDR3;                  /* SMMU_TCU_SMMU_PIDR3 */
    volatile uint32_t SMMU_CIDR0;                  /* SMMU_TCU_SMMU_CIDR0 */
    volatile uint32_t SMMU_CIDR1;                  /* SMMU_TCU_SMMU_CIDR1 */
    volatile uint32_t SMMU_CIDR2;                  /* SMMU_TCU_SMMU_CIDR2 */
    volatile uint32_t SMMU_CIDR3;                  /* SMMU_TCU_SMMU_CIDR3 */
    volatile uint32_t _pad_0x1000_0x23ff[1280];    /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_EVTYPER0;          /* SMMU_TCU_SMMU_PMCG_EVTYPER0 */
    volatile uint32_t SMMU_PMCG_EVTYPER1;          /* SMMU_TCU_SMMU_PMCG_EVTYPER1 */
    volatile uint32_t SMMU_PMCG_EVTYPER2;          /* SMMU_TCU_SMMU_PMCG_EVTYPER2 */
    volatile uint32_t SMMU_PMCG_EVTYPER3;          /* SMMU_TCU_SMMU_PMCG_EVTYPER3 */
    volatile uint32_t _pad_0x2410_0x29ff[380];     /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_SMR0;              /* SMMU_TCU_SMMU_PMCG_SMR0 */
    volatile uint32_t _pad_0x2a04_0x2bff[127];     /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_CNTENSET0;         /* SMMU_TCU_SMMU_PMCG_CNTENSET0 */
    volatile uint32_t _pad_0x2c04_0x2c1f[7];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_CNTENCLR0;         /* SMMU_TCU_SMMU_PMCG_CNTENCLR0 */
    volatile uint32_t _pad_0x2c24_0x2c3f[7];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_INTENSET0;         /* SMMU_TCU_SMMU_PMCG_INTENSET0 */
    volatile uint32_t _pad_0x2c44_0x2c5f[7];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_INTENCLR0;         /* SMMU_TCU_SMMU_PMCG_INTENCLR0 */
    volatile uint32_t _pad_0x2c64_0x2df7[101];     /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_SCR;               /* SMMU_TCU_SMMU_PMCG_SCR */
    volatile uint32_t _pad_0x2dfc_0x2dff;          /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_CFGR;              /* SMMU_TCU_SMMU_PMCG_CFGR */
    volatile uint32_t SMMU_PMCG_CR;                /* SMMU_TCU_SMMU_PMCG_CR */
    volatile uint32_t _pad_0x2e08_0x2e1f[6];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_CEID0_LO;          /* SMMU_TCU_SMMU_PMCG_CEID0_LO */
    volatile uint32_t SMMU_PMCG_CEID0_HI;          /* SMMU_TCU_SMMU_PMCG_CEID0_HI */
    volatile uint32_t SMMU_PMCG_CEID1_LO;          /* SMMU_TCU_SMMU_PMCG_CEID1_LO */
    volatile uint32_t SMMU_PMCG_CEID1_HI;          /* SMMU_TCU_SMMU_PMCG_CEID1_HI */
    volatile uint32_t _pad_0x2e30_0x2e4f[8];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_IRQ_CTRL;          /* SMMU_TCU_SMMU_PMCG_IRQ_CTRL */
    volatile uint32_t SMMU_PMCG_IRQ_CTRLACK;       /* SMMU_TCU_SMMU_PMCG_IRQ_CTRLACK */
    volatile uint32_t _pad_0x2e58_0x2e6f[6];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_AIDR;              /* SMMU_TCU_SMMU_PMCG_AIDR */
    volatile uint32_t _pad_0x2e74_0x2fb7[81];      /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_PMAUTHSTATUS;      /* SMMU_TCU_SMMU_PMCG_PMAUTHSTATUS */
    volatile uint32_t SMMU_PMCG_PMDEVARCH;         /* SMMU_TCU_SMMU_PMCG_PMDEVARCH */
    volatile uint32_t _pad_0x2fc0_0x2fcb[3];       /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_PMDEVTYPE;         /* SMMU_TCU_SMMU_PMCG_PMDEVTYPE */
    volatile uint32_t SMMU_PMCG_PIDR4;             /* SMMU_TCU_SMMU_PMCG_PIDR4 */
    volatile uint32_t SMMU_PMCG_PIDR5;             /* SMMU_TCU_SMMU_PMCG_PIDR5 */
    volatile uint32_t SMMU_PMCG_PIDR6;             /* SMMU_TCU_SMMU_PMCG_PIDR6 */
    volatile uint32_t SMMU_PMCG_PIDR7;             /* SMMU_TCU_SMMU_PMCG_PIDR7 */
    volatile uint32_t SMMU_PMCG_PIDR0;             /* SMMU_TCU_SMMU_PMCG_PIDR0 */
    volatile uint32_t SMMU_PMCG_PIDR1;             /* SMMU_TCU_SMMU_PMCG_PIDR1 */
    volatile uint32_t SMMU_PMCG_PIDR2;             /* SMMU_TCU_SMMU_PMCG_PIDR2 */
    volatile uint32_t SMMU_PMCG_PIDR3;             /* SMMU_TCU_SMMU_PMCG_PIDR3 */
    volatile uint32_t SMMU_PMCG_CIDR0;             /* SMMU_TCU_SMMU_PMCG_CIDR0 */
    volatile uint32_t SMMU_PMCG_CIDR1;             /* SMMU_TCU_SMMU_PMCG_CIDR1 */
    volatile uint32_t SMMU_PMCG_CIDR2;             /* SMMU_TCU_SMMU_PMCG_CIDR2 */
    volatile uint32_t SMMU_PMCG_CIDR3;             /* SMMU_TCU_SMMU_PMCG_CIDR3 */
    volatile uint32_t _pad_0x3000_0x7fff[5120];    /* *UNDEFINED* */
    volatile uint32_t SMMU_S_IDR0;                 /* SMMU_TCU_SMMU_S_IDR0 */
    volatile uint32_t SMMU_S_IDR1;                 /* SMMU_TCU_SMMU_S_IDR1 */
    volatile uint32_t _pad_0x8008_0x800b;          /* *UNDEFINED* */
    volatile uint32_t SMMU_S_IDR3;                 /* SMMU_TCU_SMMU_S_IDR3 */
    volatile uint32_t _pad_0x8010_0x801f[4];       /* *UNDEFINED* */
    volatile uint32_t SMMU_S_CR0;                  /* SMMU_TCU_SMMU_S_CR0 */
    volatile uint32_t SMMU_S_CR0ACK;               /* SMMU_TCU_SMMU_S_CR0ACK */
    volatile uint32_t SMMU_S_CR1;                  /* SMMU_TCU_SMMU_S_CR1 */
    volatile uint32_t SMMU_S_CR2;                  /* SMMU_TCU_SMMU_S_CR2 */
    volatile uint32_t _pad_0x8030_0x803b[3];       /* *UNDEFINED* */
    volatile uint32_t SMMU_S_INIT;                 /* SMMU_TCU_SMMU_S_INIT */
    volatile uint32_t _pad_0x8040_0x8043;          /* *UNDEFINED* */
    volatile uint32_t SMMU_S_GBPA;                 /* SMMU_TCU_SMMU_S_GBPA */
    volatile uint32_t _pad_0x8048_0x804f[2];       /* *UNDEFINED* */
    volatile uint32_t SMMU_S_IRQ_CTRL;             /* SMMU_TCU_SMMU_S_IRQ_CTRL */
    volatile uint32_t SMMU_S_IRQ_CTRLACK;          /* SMMU_TCU_SMMU_S_IRQ_CTRLACK */
    volatile uint32_t _pad_0x8058_0x805f[2];       /* *UNDEFINED* */
    volatile uint32_t SMMU_S_GERROR;               /* SMMU_TCU_SMMU_S_GERROR */
    volatile uint32_t SMMU_S_GERRORN;              /* SMMU_TCU_SMMU_S_GERRORN */
    volatile uint32_t SMMU_S_GERROR_IRQ_CFG0_LO;   /* SMMU_TCU_SMMU_S_GERROR_IRQ_CFG0_LO */
    volatile uint32_t SMMU_S_GERROR_IRQ_CFG0_HI;   /* SMMU_TCU_SMMU_S_GERROR_IRQ_CFG0_HI */
    volatile uint32_t SMMU_S_GERROR_IRQ_CFG1;      /* SMMU_TCU_SMMU_S_GERROR_IRQ_CFG1 */
    volatile uint32_t SMMU_S_GERROR_IRQ_CFG2;      /* SMMU_TCU_SMMU_S_GERROR_IRQ_CFG2 */
    volatile uint32_t _pad_0x8078_0x807f[2];       /* *UNDEFINED* */
    volatile uint32_t SMMU_S_STRTAB_BASE_LO;       /* SMMU_TCU_SMMU_S_STRTAB_BASE_LO */
    volatile uint32_t SMMU_S_STRTAB_BASE_HI;       /* SMMU_TCU_SMMU_S_STRTAB_BASE_HI */
    volatile uint32_t SMMU_S_STRTAB_BASE_CFG;      /* SMMU_TCU_SMMU_S_STRTAB_BASE_CFG */
    volatile uint32_t _pad_0x808c_0x808f;          /* *UNDEFINED* */
    volatile uint32_t SMMU_S_CMDQ_BASE_LO;         /* SMMU_TCU_SMMU_S_CMDQ_BASE_LO */
    volatile uint32_t SMMU_S_CMDQ_BASE_HI;         /* SMMU_TCU_SMMU_S_CMDQ_BASE_HI */
    volatile uint32_t SMMU_S_CMDQ_PROD;            /* SMMU_TCU_SMMU_S_CMDQ_PROD */
    volatile uint32_t SMMU_S_CMDQ_CONS;            /* SMMU_TCU_SMMU_S_CMDQ_CONS */
    volatile uint32_t SMMU_S_EVENTQ_BASE_LO;       /* SMMU_TCU_SMMU_S_EVENTQ_BASE_LO */
    volatile uint32_t SMMU_S_EVENTQ_BASE_HI;       /* SMMU_TCU_SMMU_S_EVENTQ_BASE_HI */
    volatile uint32_t SMMU_S_EVENTQ_PROD;          /* SMMU_TCU_SMMU_S_EVENTQ_PROD */
    volatile uint32_t SMMU_S_EVENTQ_CONS;          /* SMMU_TCU_SMMU_S_EVENTQ_CONS */
    volatile uint32_t SMMU_S_EVENTQ_IRQ_CFG0_LO;   /* SMMU_TCU_SMMU_S_EVENTQ_IRQ_CFG0_LO */
    volatile uint32_t SMMU_S_EVENTQ_IRQ_CFG0_HI;   /* SMMU_TCU_SMMU_S_EVENTQ_IRQ_CFG0_HI */
    volatile uint32_t SMMU_S_EVENTQ_IRQ_CFG1;      /* SMMU_TCU_SMMU_S_EVENTQ_IRQ_CFG1 */
    volatile uint32_t SMMU_S_EVENTQ_IRQ_CFG2;      /* SMMU_TCU_SMMU_S_EVENTQ_IRQ_CFG2 */
    volatile uint32_t _pad_0x80c0_0x8dff[848];     /* *UNDEFINED* */
    volatile uint32_t TCU_CTRL;                    /* SMMU_TCU_TCU_CTRL */
    volatile uint32_t TCU_QOS;                     /* SMMU_TCU_TCU_QOS */
    volatile uint32_t TCU_CFG;                     /* SMMU_TCU_TCU_CFG */
    volatile uint32_t _pad_0x8e0c_0x8e0f;          /* *UNDEFINED* */
    volatile uint32_t TCU_STATUS;                  /* SMMU_TCU_TCU_STATUS */
    volatile uint32_t _pad_0x8e14_0x8e17;          /* *UNDEFINED* */
    volatile uint32_t TCU_SCR;                     /* SMMU_TCU_TCU_SCR */
    volatile uint32_t _pad_0x8e1c_0x8e7f[25];      /* *UNDEFINED* */
    volatile uint32_t TCU_ERRFR_LO;                /* SMMU_TCU_TCU_ERRFR_LO */
    volatile uint32_t TCU_ERRFR_HI;                /* SMMU_TCU_TCU_ERRFR_HI */
    volatile uint32_t TCU_ERRCTLR_LO;              /* SMMU_TCU_TCU_ERRCTLR_LO */
    volatile uint32_t TCU_ERRCTLR_HI;              /* SMMU_TCU_TCU_ERRCTLR_HI */
    volatile uint32_t TCU_ERRSTATUS_LO;            /* SMMU_TCU_TCU_ERRSTATUS_LO */
    volatile uint32_t TCU_ERRSTATUS_HI;            /* SMMU_TCU_TCU_ERRSTATUS_HI */
    volatile uint32_t _pad_0x8e98_0x8ebf[10];      /* *UNDEFINED* */
    volatile uint32_t TCU_ERRGEN_LO;               /* SMMU_TCU_TCU_ERRGEN_LO */
    volatile uint32_t TCU_ERRGEN_HI;               /* SMMU_TCU_TCU_ERRGEN_HI */
    volatile uint32_t _pad_0x8ec8_0x8fff[78];      /* *UNDEFINED* */
    volatile uint32_t TCU_NODE_CTRL0;              /* SMMU_TCU_TCU_NODE_CTRL0 */
    volatile uint32_t TCU_NODE_CTRL1;              /* SMMU_TCU_TCU_NODE_CTRL1 */
    volatile uint32_t TCU_NODE_CTRL2;              /* SMMU_TCU_TCU_NODE_CTRL2 */
    volatile uint32_t TCU_NODE_CTRL3;              /* SMMU_TCU_TCU_NODE_CTRL3 */
    volatile uint32_t TCU_NODE_CTRL4;              /* SMMU_TCU_TCU_NODE_CTRL4 */
    volatile uint32_t TCU_NODE_CTRL5;              /* SMMU_TCU_TCU_NODE_CTRL5 */
    volatile uint32_t TCU_NODE_CTRL6;              /* SMMU_TCU_TCU_NODE_CTRL6 */
    volatile uint32_t TCU_NODE_CTRL7;              /* SMMU_TCU_TCU_NODE_CTRL7 */
    volatile uint32_t TCU_NODE_CTRL8;              /* SMMU_TCU_TCU_NODE_CTRL8 */
    volatile uint32_t TCU_NODE_CTRL9;              /* SMMU_TCU_TCU_NODE_CTRL9 */
    volatile uint32_t TCU_NODE_CTRL10;             /* SMMU_TCU_TCU_NODE_CTRL10 */
    volatile uint32_t TCU_NODE_CTRL11;             /* SMMU_TCU_TCU_NODE_CTRL11 */
    volatile uint32_t TCU_NODE_CTRL12;             /* SMMU_TCU_TCU_NODE_CTRL12 */
    volatile uint32_t TCU_NODE_CTRL13;             /* SMMU_TCU_TCU_NODE_CTRL13 */
    volatile uint32_t TCU_NODE_CTRL14;             /* SMMU_TCU_TCU_NODE_CTRL14 */
    volatile uint32_t TCU_NODE_CTRL15;             /* SMMU_TCU_TCU_NODE_CTRL15 */
    volatile uint32_t TCU_NODE_CTRL16;             /* SMMU_TCU_TCU_NODE_CTRL16 */
    volatile uint32_t TCU_NODE_CTRL17;             /* SMMU_TCU_TCU_NODE_CTRL17 */
    volatile uint32_t TCU_NODE_CTRL18;             /* SMMU_TCU_TCU_NODE_CTRL18 */
    volatile uint32_t TCU_NODE_CTRL19;             /* SMMU_TCU_TCU_NODE_CTRL19 */
    volatile uint32_t TCU_NODE_CTRL20;             /* SMMU_TCU_TCU_NODE_CTRL20 */
    volatile uint32_t TCU_NODE_CTRL21;             /* SMMU_TCU_TCU_NODE_CTRL21 */
    volatile uint32_t TCU_NODE_CTRL22;             /* SMMU_TCU_TCU_NODE_CTRL22 */
    volatile uint32_t TCU_NODE_CTRL23;             /* SMMU_TCU_TCU_NODE_CTRL23 */
    volatile uint32_t TCU_NODE_CTRL24;             /* SMMU_TCU_TCU_NODE_CTRL24 */
    volatile uint32_t TCU_NODE_CTRL25;             /* SMMU_TCU_TCU_NODE_CTRL25 */
    volatile uint32_t TCU_NODE_CTRL26;             /* SMMU_TCU_TCU_NODE_CTRL26 */
    volatile uint32_t TCU_NODE_CTRL27;             /* SMMU_TCU_TCU_NODE_CTRL27 */
    volatile uint32_t TCU_NODE_CTRL28;             /* SMMU_TCU_TCU_NODE_CTRL28 */
    volatile uint32_t TCU_NODE_CTRL29;             /* SMMU_TCU_TCU_NODE_CTRL29 */
    volatile uint32_t TCU_NODE_CTRL30;             /* SMMU_TCU_TCU_NODE_CTRL30 */
    volatile uint32_t TCU_NODE_CTRL31;             /* SMMU_TCU_TCU_NODE_CTRL31 */
    volatile uint32_t TCU_NODE_CTRL32;             /* SMMU_TCU_TCU_NODE_CTRL32 */
    volatile uint32_t TCU_NODE_CTRL33;             /* SMMU_TCU_TCU_NODE_CTRL33 */
    volatile uint32_t TCU_NODE_CTRL34;             /* SMMU_TCU_TCU_NODE_CTRL34 */
    volatile uint32_t TCU_NODE_CTRL35;             /* SMMU_TCU_TCU_NODE_CTRL35 */
    volatile uint32_t TCU_NODE_CTRL36;             /* SMMU_TCU_TCU_NODE_CTRL36 */
    volatile uint32_t TCU_NODE_CTRL37;             /* SMMU_TCU_TCU_NODE_CTRL37 */
    volatile uint32_t TCU_NODE_CTRL38;             /* SMMU_TCU_TCU_NODE_CTRL38 */
    volatile uint32_t TCU_NODE_CTRL39;             /* SMMU_TCU_TCU_NODE_CTRL39 */
    volatile uint32_t TCU_NODE_CTRL40;             /* SMMU_TCU_TCU_NODE_CTRL40 */
    volatile uint32_t TCU_NODE_CTRL41;             /* SMMU_TCU_TCU_NODE_CTRL41 */
    volatile uint32_t TCU_NODE_CTRL42;             /* SMMU_TCU_TCU_NODE_CTRL42 */
    volatile uint32_t TCU_NODE_CTRL43;             /* SMMU_TCU_TCU_NODE_CTRL43 */
    volatile uint32_t TCU_NODE_CTRL44;             /* SMMU_TCU_TCU_NODE_CTRL44 */
    volatile uint32_t TCU_NODE_CTRL45;             /* SMMU_TCU_TCU_NODE_CTRL45 */
    volatile uint32_t TCU_NODE_CTRL46;             /* SMMU_TCU_TCU_NODE_CTRL46 */
    volatile uint32_t TCU_NODE_CTRL47;             /* SMMU_TCU_TCU_NODE_CTRL47 */
    volatile uint32_t TCU_NODE_CTRL48;             /* SMMU_TCU_TCU_NODE_CTRL48 */
    volatile uint32_t TCU_NODE_CTRL49;             /* SMMU_TCU_TCU_NODE_CTRL49 */
    volatile uint32_t TCU_NODE_CTRL50;             /* SMMU_TCU_TCU_NODE_CTRL50 */
    volatile uint32_t TCU_NODE_CTRL51;             /* SMMU_TCU_TCU_NODE_CTRL51 */
    volatile uint32_t TCU_NODE_CTRL52;             /* SMMU_TCU_TCU_NODE_CTRL52 */
    volatile uint32_t TCU_NODE_CTRL53;             /* SMMU_TCU_TCU_NODE_CTRL53 */
    volatile uint32_t TCU_NODE_CTRL54;             /* SMMU_TCU_TCU_NODE_CTRL54 */
    volatile uint32_t TCU_NODE_CTRL55;             /* SMMU_TCU_TCU_NODE_CTRL55 */
    volatile uint32_t TCU_NODE_CTRL56;             /* SMMU_TCU_TCU_NODE_CTRL56 */
    volatile uint32_t TCU_NODE_CTRL57;             /* SMMU_TCU_TCU_NODE_CTRL57 */
    volatile uint32_t TCU_NODE_CTRL58;             /* SMMU_TCU_TCU_NODE_CTRL58 */
    volatile uint32_t TCU_NODE_CTRL59;             /* SMMU_TCU_TCU_NODE_CTRL59 */
    volatile uint32_t TCU_NODE_CTRL60;             /* SMMU_TCU_TCU_NODE_CTRL60 */
    volatile uint32_t TCU_NODE_CTRL61;             /* SMMU_TCU_TCU_NODE_CTRL61 */
    volatile uint32_t _pad_0x90f8_0x93ff[194];     /* *UNDEFINED* */
    volatile uint32_t TCU_NODE_STATUS0;            /* SMMU_TCU_TCU_NODE_STATUS0 */
    volatile uint32_t TCU_NODE_STATUS1;            /* SMMU_TCU_TCU_NODE_STATUS1 */
    volatile uint32_t TCU_NODE_STATUS2;            /* SMMU_TCU_TCU_NODE_STATUS2 */
    volatile uint32_t TCU_NODE_STATUS3;            /* SMMU_TCU_TCU_NODE_STATUS3 */
    volatile uint32_t TCU_NODE_STATUS4;            /* SMMU_TCU_TCU_NODE_STATUS4 */
    volatile uint32_t TCU_NODE_STATUS5;            /* SMMU_TCU_TCU_NODE_STATUS5 */
    volatile uint32_t TCU_NODE_STATUS6;            /* SMMU_TCU_TCU_NODE_STATUS6 */
    volatile uint32_t TCU_NODE_STATUS7;            /* SMMU_TCU_TCU_NODE_STATUS7 */
    volatile uint32_t TCU_NODE_STATUS8;            /* SMMU_TCU_TCU_NODE_STATUS8 */
    volatile uint32_t TCU_NODE_STATUS9;            /* SMMU_TCU_TCU_NODE_STATUS9 */
    volatile uint32_t TCU_NODE_STATUS10;           /* SMMU_TCU_TCU_NODE_STATUS10 */
    volatile uint32_t TCU_NODE_STATUS11;           /* SMMU_TCU_TCU_NODE_STATUS11 */
    volatile uint32_t TCU_NODE_STATUS12;           /* SMMU_TCU_TCU_NODE_STATUS12 */
    volatile uint32_t TCU_NODE_STATUS13;           /* SMMU_TCU_TCU_NODE_STATUS13 */
    volatile uint32_t TCU_NODE_STATUS14;           /* SMMU_TCU_TCU_NODE_STATUS14 */
    volatile uint32_t TCU_NODE_STATUS15;           /* SMMU_TCU_TCU_NODE_STATUS15 */
    volatile uint32_t TCU_NODE_STATUS16;           /* SMMU_TCU_TCU_NODE_STATUS16 */
    volatile uint32_t TCU_NODE_STATUS17;           /* SMMU_TCU_TCU_NODE_STATUS17 */
    volatile uint32_t TCU_NODE_STATUS18;           /* SMMU_TCU_TCU_NODE_STATUS18 */
    volatile uint32_t TCU_NODE_STATUS19;           /* SMMU_TCU_TCU_NODE_STATUS19 */
    volatile uint32_t TCU_NODE_STATUS20;           /* SMMU_TCU_TCU_NODE_STATUS20 */
    volatile uint32_t TCU_NODE_STATUS21;           /* SMMU_TCU_TCU_NODE_STATUS21 */
    volatile uint32_t TCU_NODE_STATUS22;           /* SMMU_TCU_TCU_NODE_STATUS22 */
    volatile uint32_t TCU_NODE_STATUS23;           /* SMMU_TCU_TCU_NODE_STATUS23 */
    volatile uint32_t TCU_NODE_STATUS24;           /* SMMU_TCU_TCU_NODE_STATUS24 */
    volatile uint32_t TCU_NODE_STATUS25;           /* SMMU_TCU_TCU_NODE_STATUS25 */
    volatile uint32_t TCU_NODE_STATUS26;           /* SMMU_TCU_TCU_NODE_STATUS26 */
    volatile uint32_t TCU_NODE_STATUS27;           /* SMMU_TCU_TCU_NODE_STATUS27 */
    volatile uint32_t TCU_NODE_STATUS28;           /* SMMU_TCU_TCU_NODE_STATUS28 */
    volatile uint32_t TCU_NODE_STATUS29;           /* SMMU_TCU_TCU_NODE_STATUS29 */
    volatile uint32_t TCU_NODE_STATUS30;           /* SMMU_TCU_TCU_NODE_STATUS30 */
    volatile uint32_t TCU_NODE_STATUS31;           /* SMMU_TCU_TCU_NODE_STATUS31 */
    volatile uint32_t TCU_NODE_STATUS32;           /* SMMU_TCU_TCU_NODE_STATUS32 */
    volatile uint32_t TCU_NODE_STATUS33;           /* SMMU_TCU_TCU_NODE_STATUS33 */
    volatile uint32_t TCU_NODE_STATUS34;           /* SMMU_TCU_TCU_NODE_STATUS34 */
    volatile uint32_t TCU_NODE_STATUS35;           /* SMMU_TCU_TCU_NODE_STATUS35 */
    volatile uint32_t TCU_NODE_STATUS36;           /* SMMU_TCU_TCU_NODE_STATUS36 */
    volatile uint32_t TCU_NODE_STATUS37;           /* SMMU_TCU_TCU_NODE_STATUS37 */
    volatile uint32_t TCU_NODE_STATUS38;           /* SMMU_TCU_TCU_NODE_STATUS38 */
    volatile uint32_t TCU_NODE_STATUS39;           /* SMMU_TCU_TCU_NODE_STATUS39 */
    volatile uint32_t TCU_NODE_STATUS40;           /* SMMU_TCU_TCU_NODE_STATUS40 */
    volatile uint32_t TCU_NODE_STATUS41;           /* SMMU_TCU_TCU_NODE_STATUS41 */
    volatile uint32_t TCU_NODE_STATUS42;           /* SMMU_TCU_TCU_NODE_STATUS42 */
    volatile uint32_t TCU_NODE_STATUS43;           /* SMMU_TCU_TCU_NODE_STATUS43 */
    volatile uint32_t TCU_NODE_STATUS44;           /* SMMU_TCU_TCU_NODE_STATUS44 */
    volatile uint32_t TCU_NODE_STATUS45;           /* SMMU_TCU_TCU_NODE_STATUS45 */
    volatile uint32_t TCU_NODE_STATUS46;           /* SMMU_TCU_TCU_NODE_STATUS46 */
    volatile uint32_t TCU_NODE_STATUS47;           /* SMMU_TCU_TCU_NODE_STATUS47 */
    volatile uint32_t TCU_NODE_STATUS48;           /* SMMU_TCU_TCU_NODE_STATUS48 */
    volatile uint32_t TCU_NODE_STATUS49;           /* SMMU_TCU_TCU_NODE_STATUS49 */
    volatile uint32_t TCU_NODE_STATUS50;           /* SMMU_TCU_TCU_NODE_STATUS50 */
    volatile uint32_t TCU_NODE_STATUS51;           /* SMMU_TCU_TCU_NODE_STATUS51 */
    volatile uint32_t TCU_NODE_STATUS52;           /* SMMU_TCU_TCU_NODE_STATUS52 */
    volatile uint32_t TCU_NODE_STATUS53;           /* SMMU_TCU_TCU_NODE_STATUS53 */
    volatile uint32_t TCU_NODE_STATUS54;           /* SMMU_TCU_TCU_NODE_STATUS54 */
    volatile uint32_t TCU_NODE_STATUS55;           /* SMMU_TCU_TCU_NODE_STATUS55 */
    volatile uint32_t TCU_NODE_STATUS56;           /* SMMU_TCU_TCU_NODE_STATUS56 */
    volatile uint32_t TCU_NODE_STATUS57;           /* SMMU_TCU_TCU_NODE_STATUS57 */
    volatile uint32_t TCU_NODE_STATUS58;           /* SMMU_TCU_TCU_NODE_STATUS58 */
    volatile uint32_t TCU_NODE_STATUS59;           /* SMMU_TCU_TCU_NODE_STATUS59 */
    volatile uint32_t TCU_NODE_STATUS60;           /* SMMU_TCU_TCU_NODE_STATUS60 */
    volatile uint32_t TCU_NODE_STATUS61;           /* SMMU_TCU_TCU_NODE_STATUS61 */
    volatile uint32_t _pad_0x94f8_0x100a7[6892];   /* *UNDEFINED* */
    volatile uint32_t SMMU_EVENTQ_PROD;            /* SMMU_TCU_SMMU_EVENTQ_PROD */
    volatile uint32_t SMMU_EVENTQ_CONS;            /* SMMU_TCU_SMMU_EVENTQ_CONS */
    volatile uint32_t _pad_0x100b0_0x100c7[6];     /* *UNDEFINED* */
    volatile uint32_t SMMU_PRIQ_PROD;              /* SMMU_TCU_SMMU_PRIQ_PROD */
    volatile uint32_t SMMU_PRIQ_CONS;              /* SMMU_TCU_SMMU_PRIQ_CONS */
    volatile uint32_t _pad_0x100d0_0x21fff[18380]; /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_EVCNTR0;           /* SMMU_TCU_SMMU_PMCG_EVCNTR0 */
    volatile uint32_t SMMU_PMCG_EVCNTR1;           /* SMMU_TCU_SMMU_PMCG_EVCNTR1 */
    volatile uint32_t SMMU_PMCG_EVCNTR2;           /* SMMU_TCU_SMMU_PMCG_EVCNTR2 */
    volatile uint32_t SMMU_PMCG_EVCNTR3;           /* SMMU_TCU_SMMU_PMCG_EVCNTR3 */
    volatile uint32_t _pad_0x22010_0x225ff[380];   /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_SVR0;              /* SMMU_TCU_SMMU_PMCG_SVR0 */
    volatile uint32_t SMMU_PMCG_SVR1;              /* SMMU_TCU_SMMU_PMCG_SVR1 */
    volatile uint32_t SMMU_PMCG_SVR2;              /* SMMU_TCU_SMMU_PMCG_SVR2 */
    volatile uint32_t SMMU_PMCG_SVR3;              /* SMMU_TCU_SMMU_PMCG_SVR3 */
    volatile uint32_t _pad_0x22610_0x22c7f[412];   /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_OVSCLR0;           /* SMMU_TCU_SMMU_PMCG_OVSCLR0 */
    volatile uint32_t _pad_0x22c84_0x22cbf[15];    /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_OVSSET0;           /* SMMU_TCU_SMMU_PMCG_OVSSET0 */
    volatile uint32_t _pad_0x22cc4_0x22d87[49];    /* *UNDEFINED* */
    volatile uint32_t SMMU_PMCG_CAPR;              /* SMMU_TCU_SMMU_PMCG_CAPR */
} smmu_regs_t;

#endif // SMMU_REGS_H__