#ifndef CCU_INTERNAL_H
#define CCU_INTERNAL_H

#include <stddef.h>
#include <stdint.h>

/*
This code controls a cadence CCU controller for an Altera Agilex5e HPS
*/

// Whole register bank access
int32_t ccu_read_regs(int32_t fd, uintptr_t args, size_t length);
int32_t ccu_write_regs(int32_t fd, uintptr_t args, size_t length);

int32_t ccu_dsu_get_caiuidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiufuidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutcr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutcr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuedr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuuedr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuueir_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuueir_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuuesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuuelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuuelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuuesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucrtr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucrtr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutocr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutocr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuqoscr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuqoscr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuqossr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuqossr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_nrsbar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_nrsbar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_nrsbhr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_nrsbhr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_nrsblr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_nrsblr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiubrar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiubrar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiubrblr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiubrblr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiubrbhr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiubrbhr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuamigr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiuamigr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiumifsr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiumifsr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprar0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprar0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprblr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprblr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprbhr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprbhr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprar1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprar1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprblr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprblr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprbhr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprbhr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprar2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprar2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprblr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprblr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprbhr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprbhr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprar11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprar11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprblr11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprblr11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiugprbhr11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiugprbhr11_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucctrlr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucctrlr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutctrlr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutctrlr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutbalr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutbalr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutbahr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutbahr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutopcr00_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutopcr00_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutopcr10_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutopcr10_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutubr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutubr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiutubmr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiutubmr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntcr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntcr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntvr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntvr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntsr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntsr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntcr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntcr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntvr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntvr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntsr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntsr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntcr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntcr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntvr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntvr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntsr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntsr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntcr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntcr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntvr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntvr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiucntsr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiucntsr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiunrsar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_set_caiunrsar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuuevir_reg(int32_t fd, uintptr_t args);
int32_t ccu_dsu_get_caiuinfor_reg(int32_t fd, uintptr_t args);
int32_t ccu_ncaiu_get_xaiuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiufuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucrtr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucrtr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuqoscr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuqoscr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuqossr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuqossr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiunrsbar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiunrsbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiunrsbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiunrsblr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiubrar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiubrar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiubrblr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiubrblr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiubrbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiubrbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuamigr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuamigr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiumifsr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiumifsr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprar11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprar11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprblr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprblr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiugprbhr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiugprbhr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutbalr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutbalr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutbahr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutbahr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutopcr00_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutopcr00_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutopcr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutopcr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutubr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutubr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutubmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutubmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiutctrlr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiutctrlr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuedr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiuedr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiucntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_set_xaiucntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiunrsar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuengidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_ncaiu_get_xaiuinfor_reg(int32_t fd, uintptr_t args, int32_t reg_offset);

int32_t ccu_dce_get_dceuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceufuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceutcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceutcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceutar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuser0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuser0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuqoscr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuqoscr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceusfmcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceusfmcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceusfmar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceubrar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceubrar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceubrblr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceubrblr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceubrbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceubrbhr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuamigr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuamigr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceumifsr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceumifsr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr4_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr5_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr6_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr7_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr8_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr9_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr10_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprar11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprar11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprblr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprblr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceugprbhr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceugprbhr11_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuedr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuedr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcecntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcecntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuccr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuccr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuccr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dceuccr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dcemcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_set_dcemcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceusbsir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuengidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dce_get_dceuinfor_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiufuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiutar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiucecr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiucesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiucelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiucelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiucesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiutocr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuqoscr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiuqoscr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmctcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmctcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmctar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcapr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmcapr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcisr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcmcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmcmcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcmar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcmlr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmcmlr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcmlr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmcmlr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcmdr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmiusmcmdr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmicntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmicntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntfr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntfr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntfr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntfr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntmr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntmr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntfr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntfr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntmr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntmr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntfr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntfr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmibcntmr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmibcntmr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmilcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmilcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmimcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_set_dmimcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_mrdsbsir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_cmdsbsir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuevidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiusmcifr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dmi_get_dmiuinfor_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiufuidr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiutar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuuedr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuueir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuuesr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuuelr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuuelr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diiuuesar_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicctrlr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntcr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntvr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntsr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntcr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntvr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntsr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntcr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntvr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntsr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntcr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntvr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diicntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diicntsr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntfr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntfr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntmr0_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntfr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntfr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntmr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntmr1_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntfr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntfr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntmr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntmr2_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntfr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntfr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diibcntmr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diibcntmr3_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diilcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diilcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diimcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_set_diimcntcr_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiusbsir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuuevir_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dii_get_diiuinfor_reg(int32_t fd, uintptr_t args, int32_t reg_offset);
int32_t ccu_dve_get_dveuidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveufuidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveutar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvececr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvececr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuuedr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuuedr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuueir_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuueir_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuuesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuuesr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuuelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuuelr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuuelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuuelr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuesar_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveucrtr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveucrtr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuser0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuser0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetascr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvetascr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetadhr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetadtsr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad0r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad1r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad2r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad3r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad4r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad5r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad6r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad7r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad8r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad9r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad10r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad11r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad12r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad13r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad14r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvetad15r_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntcr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntcr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntvr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntvr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntsr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntsr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntcr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntcr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntvr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntvr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntsr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntsr1_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntcr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntcr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntvr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntvr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntsr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntsr2_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntcr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntcr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntvr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntvr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvecntsr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvecntsr3_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dvemcntcr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dvemcntcr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuengdbr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_set_dveuengdbr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuengidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_dve_get_dveuinfor_reg(int32_t fd, uintptr_t args);

int32_t ccu_sys_global_get_grbucssfidr0_reg(int32_t fd, uintptr_t args);
int32_t ccu_sys_global_get_grbunrrir_reg(int32_t fd, uintptr_t args);
int32_t ccu_sys_global_get_grbuengidr_reg(int32_t fd, uintptr_t args);
int32_t ccu_sys_global_get_grbunrrucr_reg(int32_t fd, uintptr_t args);
int32_t ccu_sys_global_get_grbunsidr_reg(int32_t fd, uintptr_t args);

#endif // CCU_INTERNAL_H